spring.application.name=clone


spring.datasource.url=jdbc:postgresql://localhost:5432/blinkit?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=456123456

#JPA configurations
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=ALWAYS
#spring.sql.init.data-locations=classpath:data.sql


spring.data.redis.host=localhost
spring.data.redis.port=6379


jwt.secret=EcyyfFyxDdcPa07MmGI5JSQ3DAeIUCAENlOX257+FVo=
jwt.expiration-ms=86400000



admin.seed.email=admin@blinkit.com
admin.seed.password=Admin@1234